/*
-- Query: select * from users
LIMIT 0, 1000

-- Date: 2020-02-24 02:11
*/
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('1',1,'김동욱','123','관리자','https://block-board-user.s3.amazonaws.com/dongwook.jpg','dongwook.jpg','https://block-board-user-thumbnail.s3.amazonaws.com/dongwook.jpg','dongwook.jpg');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('2',1,'전우혁','123','관리자','https://block-board-user.s3.amazonaws.com/woohyuk.jpg','woohyuk.jpg','https://block-board-user-thumbnail.s3.amazonaws.com/woohyuk.jpg','woohyuk.jpg');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('admin',1,'관리자','123','관리자','https://block-board-user.s3.amazonaws.com/admin.png','admin.png','https://block-board-user-thumbnail.s3.amazonaws.com/admin.png','admin.png');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('aldhkdizl',1,'미와야키사쿠라','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/aldhkdizl.PNG','aldhkdizl.PNG','https://block-board-user-thumbnail.s3.amazonaws.com/aldhkdizl.PNG','aldhkdizl.PNG');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('chldPsk',1,'최예나','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/chldPsk.PNG','chldPsk.PNG','https://block-board-user-thumbnail.s3.amazonaws.com/chldPsk.PNG','chldPsk.PNG');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('cksduf',1,'찬열','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/cksduf.jpg','cksduf.jpg','https://block-board-user-thumbnail.s3.amazonaws.com/cksduf.jpg','cksduf.jpg');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('cps',1,'첸','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/cps.jpg','cps.jpg','https://block-board-user-thumbnail.s3.amazonaws.com/cps.jpg','cps.jpg');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('dbfl',1,'유리','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/dbfl.jpg','dbfl.jpg','https://block-board-user-thumbnail.s3.amazonaws.com/dbfl.jpg','dbfl.jpg');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('dbsdk',1,'윤아','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/dbsdk.jfif','dbsdk.jfif','','dbsdk.jfif');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('dhgkdud',1,'오하영','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/dhgkdud.PNG','dhgkdud.PNG','https://block-board-user-thumbnail.s3.amazonaws.com/dhgkdud.PNG','dhgkdud.PNG');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('dkqnzlskzh',1,'아부키나코','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/dkqnzlskzh.PNG','dkqnzlskzh.PNG','https://block-board-user-thumbnail.s3.amazonaws.com/dkqnzlskzh.PNG','dkqnzlskzh.PNG');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('dksdbwls',1,'안유진','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/dksdbwls.PNG','dksdbwls.PNG','https://block-board-user-thumbnail.s3.amazonaws.com/dksdbwls.PNG','dksdbwls.PNG');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('dlcodus',1,'이채연','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/dlcodus.PNG','dlcodus.PNG','https://block-board-user-thumbnail.s3.amazonaws.com/dlcodus.PNG','dlcodus.PNG');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('eldh',1,'디오','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/eldh.jfif','eldh.jfif','','eldh.jfif');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('fhwp',1,'로제','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/fhwp.jfif','fhwp.jfif','','fhwp.jfif');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('fltk',1,'리사','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/fltk.PNG','fltk.PNG','https://block-board-user-thumbnail.s3.amazonaws.com/fltk.PNG','fltk.PNG');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('foqahstmxj',1,'랩몬스터','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/foqahstmxj.jfif','foqahstmxj.jfif','','foqahstmxj.jfif');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('fpdl',1,'레이','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/fpdl.jpg','fpdl.jpg','https://block-board-user-thumbnail.s3.amazonaws.com/fpdl.jpg','fpdl.jpg');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('ghsekglxhal',1,'혼다히토미','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/ghsekglxhal.PNG','ghsekglxhal.PNG','https://block-board-user-thumbnail.s3.amazonaws.com/ghsekglxhal.PNG','ghsekglxhal.PNG');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('gydus',1,'효연','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/gydus.jpg','gydus.jpg','https://block-board-user-thumbnail.s3.amazonaws.com/gydus.jpg','gydus.jpg');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('irene',1,'아이린','123','일반','https://block-board-user.s3.amazonaws.com/irene.jpg','irene.jpg','https://block-board-user-thumbnail.s3.amazonaws.com/irene.jpg','irene.jpg');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('joy',1,'조이','123','일반','https://block-board-user.s3.amazonaws.com/joy.jpg','joy.jpg','https://block-board-user-thumbnail.s3.amazonaws.com/joy.jpg','joy.jpg');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('qnl',1,'뷔','1qaz2wsx!','일반',NULL,NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('qorgus',1,'백현','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/qorgus.jfif','qorgus.jfif','','qorgus.jfif');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('rkdgPdnjs',1,'강혜원','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/rkdgPdnjs.PNG','rkdgPdnjs.PNG','https://block-board-user-thumbnail.s3.amazonaws.com/rkdgPdnjs.PNG','rkdgPdnjs.PNG');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('rlacodnjs',1,'김채원','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/rlacodnjs.PNG','rlacodnjs.PNG','https://block-board-user-thumbnail.s3.amazonaws.com/rlacodnjs.PNG','rlacodnjs.PNG');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('rlaskawn',1,'김남주','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/rlaskawn.PNG','rlaskawn.PNG','https://block-board-user-thumbnail.s3.amazonaws.com/rlaskawn.PNG','rlaskawn.PNG');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('rnjsdmsql',1,'권은비','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/rnjsdmsql.PNG','rnjsdmsql.PNG','https://block-board-user-thumbnail.s3.amazonaws.com/rnjsdmsql.PNG','rnjsdmsql.PNG');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('seulgi',1,'슬기','123','일반','https://block-board-user.s3.amazonaws.com/seulgi.jpg','seulgi.jpg','https://block-board-user-thumbnail.s3.amazonaws.com/seulgi.jpg','seulgi.jpg');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('tbrk',1,'슈가','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/tbrk.jpg','tbrk.jpg','https://block-board-user-thumbnail.s3.amazonaws.com/tbrk.jpg','tbrk.jpg');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('thsskdms',1,'손나은','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/thsskdms.PNG','thsskdms.PNG','https://block-board-user-thumbnail.s3.amazonaws.com/thsskdms.PNG','thsskdms.PNG');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('tjgus',1,'서현','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/tjgus.jpg','tjgus.jpg','https://block-board-user-thumbnail.s3.amazonaws.com/tjgus.jpg','tjgus.jpg');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('Tjsl',1,'써니','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/Tjsl.jpg','Tjsl.jpg','https://block-board-user-thumbnail.s3.amazonaws.com/Tjsl.jpg','Tjsl.jpg');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('tldnals',1,'시우민','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/tldnals.jpg','tldnals.jpg','https://block-board-user-thumbnail.s3.amazonaws.com/tldnals.jpg','tldnals.jpg');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('tndud',1,'수영','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/tndud.jpg','tndud.jpg','https://block-board-user-thumbnail.s3.amazonaws.com/tndud.jpg','tndud.jpg');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('tngh',1,'수호','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/tngh.jpg','tngh.jpg','https://block-board-user-thumbnail.s3.amazonaws.com/tngh.jpg','tngh.jpg');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('tpgns',1,'세훈','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/tpgns.jpg','tpgns.jpg','https://block-board-user-thumbnail.s3.amazonaws.com/tpgns.jpg','tpgns.jpg');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('wendy',1,'웬디','123','일반','https://block-board-user.s3.amazonaws.com/wendy.png','wendy.png','https://block-board-user-thumbnail.s3.amazonaws.com/wendy.png','wendy.png');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('whdbfl',1,'조유리','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/whdbfl.PNG','whdbfl.PNG','https://block-board-user-thumbnail.s3.amazonaws.com/whdbfl.PNG','whdbfl.PNG');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('wjddmswl',1,'정은지','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/wjddmswl.PNG','wjddmswl.PNG','https://block-board-user-thumbnail.s3.amazonaws.com/wjddmswl.PNG','wjddmswl.PNG');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('wjdrnr',1,'정국','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/wjdrnr.jfif','wjdrnr.jfif','','wjdrnr.jfif');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('wkddnjsdud',1,'장원영','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/wkddnjsdud.PNG','wkddnjsdud.PNG','https://block-board-user-thumbnail.s3.amazonaws.com/wkddnjsdud.PNG','wkddnjsdud.PNG');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('wlals',1,'지민','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/wlals.jpg','wlals.jpg','https://block-board-user-thumbnail.s3.amazonaws.com/wlals.jpg','wlals.jpg');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('wls',1,'진','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/wls.jpg','wls.jpg','https://block-board-user-thumbnail.s3.amazonaws.com/wls.jpg','wls.jpg');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('wltn',1,'지수','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/wltn.jpg','wltn.jpg','https://block-board-user-thumbnail.s3.amazonaws.com/wltn.jpg','wltn.jpg');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('wpdlghq',1,'제이홉','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/wpdlghq.jpg','wpdlghq.jpg','https://block-board-user-thumbnail.s3.amazonaws.com/wpdlghq.jpg','wpdlghq.jpg');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('wpsl',1,'제니','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/wpsl.jpg','wpsl.jpg','https://block-board-user-thumbnail.s3.amazonaws.com/wpsl.jpg','wpsl.jpg');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('wptlzk',1,'제시카','1qaz2wxx!','일반','https://block-board-user.s3.amazonaws.com/wptlzk.jfif','wptlzk.jfif','','wptlzk.jfif');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('xlvksl',1,'티파니','1qaz2wsx!','일반','https://block-board-user.s3.amazonaws.com/xlvksl.jpg','xlvksl.jpg','https://block-board-user-thumbnail.s3.amazonaws.com/xlvksl.jpg','xlvksl.jpg');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('yeri',1,'예리','123','일반','https://block-board-user.s3.amazonaws.com/yeri.jpg','yeri.jpg','https://block-board-user-thumbnail.s3.amazonaws.com/yeri.jpg','yeri.jpg');
INSERT INTO `` (`user_id`,`company_id`,`user_name`,`user_password`,`user_type`,`image_url`,`image_file_name`,`thumbnail_url`,`thumbnail_file_name`) VALUES ('zkdl',1,'카이','1qaz2wx!','일반','https://block-board-user.s3.amazonaws.com/zkdl.jpg','zkdl.jpg','https://block-board-user-thumbnail.s3.amazonaws.com/zkdl.jpg','zkdl.jpg');
